[package]
name = "binlog"
version = "0.1.0"
edition = "2021"

[features]
default = []
sqlite = ["rusqlite", "zstd"]

[dependencies]
refcount-interner = "0.2.4"
rusqlite = { version = "0.27.0", optional = true }
zstd = { version = "0.11.1+zstd.1.5.2", optional = true }
