name: Python test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - { os: macOS-latest }
        - { os: ubuntu-latest }
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"
      - name: Install dependencies
        run: pip install maturin pytest
        run: maturin develop --cargo-extra-args="--all-features"
      - name: Test
        run: pytest --color=yes python_tests/
