name: Rust tests

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - { rust: stable, os: macOS-latest }
        - { rust: stable, os: ubuntu-latest }
        - { rust: nightly, os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - run: cargo test
      - run: cd fuzz && cargo check
      - run: cargo clippy
      - run: cargo fmt -- --check
